using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;

namespace TeklaDump.Attributes.ReportJoin;

/// <summary>
/// Generates the <c>.rpt</c> that the T2 path runs: one row per content type, each emitting
/// <c>GUID</c> plus the requested attributes as a semicolon-delimited line.
/// </summary>
/// <remarks>
/// <para>
/// The Template Editor's file format is a nested block syntax, and the shape below is the minimum
/// that produces parseable output: a <c>TEXTUAL</c> template, <c>usecolumns = FALSE</c> so fields
/// land where their <c>location</c> says, and <c>sorttype = DISTINCT</c> so every object gets its
/// own row rather than being merged with an identical sibling — a COMBINE row would silently
/// collapse two identical parts into one and lose a GUID.
/// </para>
/// <para>
/// Every line starts with a literal <c>TD</c> tag and the content type, so the parser can ignore
/// page furniture and tell a PART row from a BOLT row without counting columns.
/// </para>
/// </remarks>
internal static class ReportTemplateWriter
{
    /// <summary>The literal that marks a line this tool wrote. Anything else in the report is noise.</summary>
    public const string RowTag = "TD";

    public const char Separator = ';';

    /// <summary>Wide enough for a braced GUID plus room to spare.</summary>
    private const int GuidFieldLength = 40;

    private const int StringFieldLength = 48;
    private const int NumberFieldLength = 24;

    /// <summary>Decimals on a FLOAT field. Six matches the rounding the JSON writer applies.</summary>
    private const int Decimals = 6;

    /// <summary>
    /// Builds the template text.
    /// </summary>
    /// <param name="templateName">
    /// Goes into the template's own <c>name</c> field and must match the file name Tekla resolves.
    /// </param>
    /// <param name="rows">One entry per content type present in the input set.</param>
    public static string Build(string templateName, IReadOnlyList<ReportRowSpec> rows)
    {
        var builder = new StringBuilder();
        builder.Append("template\n{\n");
        Field(builder, 1, "name", Quoted(templateName));
        Field(builder, 1, "type", "TEXTUAL");
        Field(builder, 1, "width", "512");
        Field(builder, 1, "maxheight", "120");
        Field(builder, 1, "columns", "(1, 1)");
        Field(builder, 1, "gap", "1");
        Field(builder, 1, "fillpolicy", "EVEN");
        Field(builder, 1, "filldirection", "HORIZONTAL");
        Field(builder, 1, "fillstartfrom", "TOPLEFT");
        Field(builder, 1, "margins", "(0, 0, 0, 0)");
        Field(builder, 1, "gridxspacing", "1");
        Field(builder, 1, "gridyspacing", "1");
        Field(builder, 1, "version", "5.2");
        Field(builder, 1, "notes", Quoted("Generated by TeklaDump for a report join. Safe to delete."));

        for (var i = 0; i < rows.Count; i++)
            AppendRow(builder, rows[i], i);

        builder.Append("};\n");
        return builder.ToString();
    }

    private static void AppendRow(StringBuilder builder, ReportRowSpec row, int index)
    {
        builder.Append("\n    row _tmp_").Append(index.ToString(CultureInfo.InvariantCulture)).Append("\n    {\n");
        Field(builder, 2, "name", Quoted(row.ContentType));
        Field(builder, 2, "height", "1");
        Field(builder, 2, "visibility", "TRUE");
        Field(builder, 2, "usecolumns", "FALSE");
        Field(builder, 2, "rule", "\"\"");
        Field(builder, 2, "contenttype", Quoted(row.ContentType));
        Field(builder, 2, "sorttype", "DISTINCT");

        var x = 0;
        x = AppendText(builder, "tag" + index, x, RowTag + Separator + row.ContentType + Separator);
        x = AppendValueField(builder, "GUID", "GUID", "STRING", GuidFieldLength, x);

        for (var i = 0; i < row.Attributes.Count; i++)
        {
            var attribute = row.Attributes[i];
            x = AppendText(builder, "sep" + index + "_" + i, x, Separator.ToString());
            x = AppendValueField(
                builder,
                // Field names must be unique within a row and are not the attribute name Tekla
                // queries — the formula is. A positional name keeps a dotted attribute from
                // producing an invalid field name.
                "f" + i.ToString(CultureInfo.InvariantCulture),
                attribute.Name,
                DataTypeOf(attribute.ValueType),
                LengthOf(attribute.ValueType),
                x);
        }

        builder.Append("    };\n");
    }

    private static int AppendText(StringBuilder builder, string name, int x, string text)
    {
        builder.Append("\n        text\n        {\n");
        Field(builder, 3, "name", Quoted(name));
        Field(builder, 3, "x1", x.ToString(CultureInfo.InvariantCulture));
        Field(builder, 3, "y1", "0");
        Field(builder, 3, "x2", x.ToString(CultureInfo.InvariantCulture));
        Field(builder, 3, "y2", "0");
        Field(builder, 3, "string", Quoted(text));
        AppendFont(builder);
        Field(builder, 3, "justify", "LEFT");
        Field(builder, 3, "pen", "0");
        builder.Append("        };\n");
        return x + text.Length;
    }

    private static int AppendValueField(
        StringBuilder builder, string fieldName, string attributeName, string dataType, int length, int x)
    {
        builder.Append("\n        valuefield\n        {\n");
        Field(builder, 3, "name", Quoted(fieldName));
        Field(builder, 3, "location", "(" + x.ToString(CultureInfo.InvariantCulture) + ", 0)");
        // The formula is where the attribute name actually goes. Escaped quotes, because the
        // formula is itself a quoted string in this format.
        Field(builder, 3, "formula", "\"GetValue(\\\"" + attributeName + "\\\")\"");
        Field(builder, 3, "datatype", dataType);
        Field(builder, 3, "class", "\"\"");
        Field(builder, 3, "cacheable", "TRUE");
        Field(builder, 3, "justify", "LEFT");
        Field(builder, 3, "visibility", "TRUE");
        Field(builder, 3, "angle", "0");
        Field(builder, 3, "length", length.ToString(CultureInfo.InvariantCulture));
        if (dataType == "DOUBLE")
            Field(builder, 3, "decimals", Decimals.ToString(CultureInfo.InvariantCulture));
        Field(builder, 3, "sortdirection", "NONE");
        AppendFont(builder);
        Field(builder, 3, "pen", "0");
        Field(builder, 3, "oncombine", "NONE");
        builder.Append("        };\n");
        return x + length;
    }

    private static void AppendFont(StringBuilder builder)
    {
        // Courier New at a fixed size: the output is parsed, not read, and a proportional font is
        // what makes a TEXTUAL report's columns drift.
        Field(builder, 3, "fontname", Quoted("Courier New"));
        Field(builder, 3, "fontcolor", "153");
        Field(builder, 3, "fonttype", "2");
        Field(builder, 3, "fontsize", "0.8");
        Field(builder, 3, "fontratio", "0.75");
        Field(builder, 3, "fontslant", "0");
        Field(builder, 3, "fontstyle", "0");
    }

    private static string DataTypeOf(TemplateValueType valueType)
    {
        switch (valueType)
        {
            case TemplateValueType.Float: return "DOUBLE";
            case TemplateValueType.Integer: return "INTEGER";
            default: return "STRING";
        }
    }

    private static int LengthOf(TemplateValueType valueType) =>
        valueType == TemplateValueType.Character ? StringFieldLength : NumberFieldLength;

    private static void Field(StringBuilder builder, int indent, string name, string value)
    {
        builder.Append(' ', indent * 4).Append(name).Append(" = ").Append(value).Append(";\n");
    }

    private static string Quoted(string value) => "\"" + value.Replace("\"", "\\\"") + "\"";
}

/// <summary>One content type's row: the type and the attributes valid for it.</summary>
internal sealed class ReportRowSpec
{
    public ReportRowSpec(string contentType, IReadOnlyList<TemplateAttributeDefinition> attributes)
    {
        ContentType = contentType;
        Attributes = attributes;
    }

    public string ContentType { get; }

    /// <summary>
    /// Only attributes the catalog declares for THIS content type. A requested attribute that does
    /// not apply is left out of the row and reported as null for those objects with one warning,
    /// rather than being written into the template and failing the whole report.
    /// </summary>
    public IReadOnlyList<TemplateAttributeDefinition> Attributes { get; }
}
